#!/usr/bin/env node
// build_seo_pages.mjs — free-tools SEO surface generator (H6318)
//
// Regenerate the committed site/ tree from verses/ + the app's own engines:
//   node tools/build_seo_pages.mjs
//
// Emits (all under site/, shipped by .github/workflows/pages.yml):
//   site/sitemap.xml, site/robots.txt
//   site/tools/index.html                        — free-tools hub + verse library grid
//   site/tools/meter-detector/index.html         — paste-a-shloka metre detector + wave diagram
//   site/tools/meter-detector/assets/meter.js    — VERBATIM extraction from src/scripts/app.js
//   site/tools/encoding-converter/index.html     — Devanagari ↔ IAST converter
//   site/tools/encoding-converter/assets/schemes.js — VERBATIM extraction from src/scripts/app.js
//   site/tools/assets/translit.js                — verbatim copy of src/core/translit.js (portability)
//   site/verse/<id>/index.html                   — landing page per verses/data/*.json
//
// Engine reuse (no re-implementation, per tools/test_meter_detector.py precedent):
//   IAST + syllables + guru/laghu come from the live src/core/translit.js module;
//   metre identification and scheme transliteration are extracted VERBATIM from
//   src/scripts/app.js by brace matching (consts + DOM-free functions only).
// The generator self-checks and exits non-zero on any drift or broken link.

import { readFileSync, writeFileSync, mkdirSync, existsSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';
import { devToIast, syllabifyIast } from '../src/core/translit.js';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..');
const SITE = join(ROOT, 'site');
const BASE = 'https://gasyoun.github.io/SanskritKaraoke';
const TODAY_ISO = '2026-10-09';

// ── brace-matching extraction from app.js ────────────────────────────────────

const PAIRS = { '{': '}', '(': ')', '[': ']' };

function prevSig(text, i) {
  let j = i - 1;
  while (j >= 0 && /\s/.test(text[j])) j--;
  return j >= 0 ? text[j] : '';
}

function matchDelimiter(text, start) {
  // start points at an opener; return index of its matching closer.
  // Skips ' " ` strings, // and /* */ comments, and regex literals
  // (division vs regex decided by the previous significant character).
  const open = text[start], close = PAIRS[open];
  let depth = 0, inStr = null;
  for (let i = start; i < text.length; i++) {
    const c = text[i], n = text[i + 1];
    if (inStr) {
      if (c === '\\') { i++; continue; }
      if (c === inStr) inStr = null;
      continue;
    }
    if (c === "'" || c === '"' || c === '`') { inStr = c; continue; }
    if (c === '/' && n === '/') { while (i < text.length && text[i] !== '\n') i++; continue; }
    if (c === '/' && n === '*') {
      i += 2;
      while (i < text.length && !(text[i] === '*' && text[i + 1] === '/')) i++;
      continue;
    }
    if (c === '/' && /[([{=:,;!&|?~^+\-*%<>^-]/.test(prevSig(text, i))) {
      // regex literal — skip to its closing slash, honouring [...] classes
      let j = i + 1, inClass = false;
      while (j < text.length) {
        const rc = text[j];
        if (rc === '\\') { j += 2; continue; }
        if (rc === '[') inClass = true;
        else if (rc === ']') inClass = false;
        else if (rc === '/' && !inClass) break;
        j++;
      }
      i = j + 1;
      continue;
    }
    if (c === open) depth++;
    else if (c === close) { depth--; if (depth === 0) return i; }
  }
  throw new Error(`unbalanced ${open} at offset ${start}`);
}

function extractConst(src, name) {
  const m = src.match(new RegExp(`\\bconst ${name}\\s*=`));
  if (!m) throw new Error(`const ${name} not found`);
  let i = m.index + m[0].length;
  while (/\s/.test(src[i])) i++;
  if (!PAIRS[src[i]]) throw new Error(`const ${name}: no opener at ${src.slice(i, i + 12)}`);
  const end = matchDelimiter(src, i);
  return `export const ${name} = ` + src.slice(i, end + 1) + ';';
}

function extractRawLine(src, pattern) {
  // extract a `const NAME = <expr>;` whose expr may open with ( [ or {
  const m = src.match(pattern);
  if (!m) throw new Error(`pattern not found: ${pattern}`);
  let i = m.index + m[0].length;
  while (/\s/.test(src[i])) i++;
  if (!PAIRS[src[i]]) throw new Error(`no opener after pattern at offset ${i}`);
  const end = matchDelimiter(src, i);
  return 'export ' + src.slice(m.index, end + 1) + ';';
}

function extractFunction(src, name) {
  const m = src.match(new RegExp(`\\bfunction ${name}\\s*\\(`));
  if (!m) throw new Error(`function ${name} not found`);
  let i = m.index;
  while (src[i] !== '{') i++;
  const end = matchDelimiter(src, i);
  return 'export ' + src.slice(m.index, end + 1);
}

const appSrc = readFileSync(join(ROOT, 'src/scripts/app.js'), 'utf8');

const meterJs = [
  '// GENERATED by tools/build_seo_pages.mjs — do not edit by hand.',
  '// Verbatim extraction of the metre engine from src/scripts/app.js',
  '// (METER_DATA, syllabifySlp, scanWeights, gaRaAbbrev, chooseHeavy,',
  '//  morePerLine, identifyMeterLocal). Regenerate:',
  '//   node tools/build_seo_pages.mjs',
  '// Behavioural parity is canaried in this generator and by tools/test_meter_detector.py.',
  '',
  extractConst(appSrc, 'METER_DATA'),
  '',
  extractRawLine(appSrc, /\bconst SLP_CONS\s*=\s*new Set/),
  '',
  extractFunction(appSrc, 'syllabifySlp'),
  '',
  extractFunction(appSrc, 'scanWeights'),
  '',
  'export ' + appSrc.match(/\bconst GANAS\s*=\s*METER_DATA\.gaRas;/)[0],
  '',
  extractFunction(appSrc, 'gaRaAbbrev'),
  '',
  extractFunction(appSrc, 'chooseHeavy'),
  '',
  extractFunction(appSrc, 'morePerLine'),
  '',
  extractFunction(appSrc, 'identifyMeterLocal'),
  '',
].join('\n');

const schemesJs = [
  '// GENERATED by tools/build_seo_pages.mjs — do not edit by hand.',
  '// Verbatim extraction of the transliteration engine from src/scripts/app.js',
  '// (SCHEME_MAPS, SCHEME_NAMES, TRL, detectScheme, mapReplace, slpToDev,',
  '//  normalizePunctuation, transliterateToDev).',
  '// TRL is ported from skrutable, CC BY-SA 4.0 — attribution preserved.',
  '// Regenerate: node tools/build_seo_pages.mjs',
  '',
  extractConst(appSrc, 'SCHEME_MAPS'),
  '',
  extractConst(appSrc, 'SCHEME_NAMES'),
  '',
  extractConst(appSrc, 'TRL'),
  '',
  extractFunction(appSrc, 'detectScheme'),
  '',
  extractFunction(appSrc, 'mapReplace'),
  '',
  extractFunction(appSrc, 'slpToDev'),
  '',
  extractFunction(appSrc, 'normalizePunctuation'),
  '',
  extractFunction(appSrc, 'transliterateToDev'),
  '',
].join('\n');

// ── verse corpus ──────────────────────────────────────────────────────────────

const index = JSON.parse(readFileSync(join(ROOT, 'verses/index.json'), 'utf8'));
const verseIds = index.verses.map(v => v.id);
const verses = verseIds.map(id => {
  const p = join(ROOT, 'verses/data', `${id}.json`);
  if (!existsSync(p)) throw new Error(`index.json lists ${id} but verses/data/${id}.json is missing`);
  return JSON.parse(readFileSync(p, 'utf8'));
});

const OK_RIGHTS = new Set(['own-work', 'cleared', 'public-domain']);

function publishableTranslations(v) {
  const tr = v.translation || {};
  const rights = tr.rights || {};
  const out = [];
  for (const lang of Object.keys(tr)) {
    if (lang === 'provenance' || lang === 'rights') continue;
    const st = rights[lang]?.status;
    if (st && OK_RIGHTS.has(st)) {
      out.push({ lang, text: tr[lang], status: st, rights: rights[lang] });
    }
  }
  return out;
}

const LANG_LABEL = { ru: 'Русский (RU)', en: 'English (EN)', de: 'Deutsch (DE)' };

// ── HTML helpers ──────────────────────────────────────────────────────────────

const esc = s => String(s ?? '')
  .replaceAll('&', '&amp;').replaceAll('<', '&lt;').replaceAll('>', '&gt;')
  .replaceAll('"', '&quot;');

const stripDanda = s => (s || '').replace(/[।॥.]+/g, '').trim();

function waveSvg(lineIast) {
  const syls = syllabifyIast(lineIast);
  if (!syls.length) return '';
  const W = Math.max(240, syls.length * 44 + 40), H = 96;
  const step = (W - 40) / syls.length;
  let pts = '', labels = '';
  syls.forEach((s, i) => {
    const x = 20 + step * i + step / 2;
    const guru = s.type === 'guru';
    const y = guru ? 14 : 62;
    pts += `${x},${y} `;
    labels += `<text x="${x}" y="88" text-anchor="middle" font-size="13" fill="${guru ? '#8B0000' : '#2C4A1E'}" font-family="ui-monospace,monospace">${esc(s.syl)}</text>`;
  });
  return `<svg class="wave" viewBox="0 0 ${W} ${H}" role="img" aria-label="syllable wave: guru high, laghu low">` +
    `<polyline points="${pts.trim()}" fill="none" stroke="#b07c18" stroke-width="2"/>` +
    pts.trim().split(' ').map(p => { const [x, y] = p.split(',');
      return `<circle cx="${x}" cy="${y}" r="4.5" fill="${y === '14' ? '#8B0000' : '#2C4A1E'}"/>`;
    }).join('') + labels + '</svg>';
}

function ctaFooter(campaign) {
  return `<footer class="cta-footer">
  <a class="cta-btn" href="https://samskrtam.ru/usha-sanka?utm_source=karaoke&amp;utm_medium=cta&amp;utm_campaign=${esc(campaign)}" target="_blank" rel="noopener">Записаться на курс санскрита →</a>
  <span class="cta-hint">Можно в записи и в своём темпе</span>
  <a class="cta-link" href="https://t.me/rusamskrtam" target="_blank" rel="noopener">Задать вопрос в Telegram</a>
</footer>`;
}

const PAGE_CSS = `
:root{--bg:#f7f3ec;--bg2:#ede7db;--ink:#18120c;--ink2:#6b5c4e;--card:#fff;--border:#cfc5b2;--accent:#7a1515;--gold:#b07c18}
*{box-sizing:border-box}body{margin:0;font-family:Georgia,'Times New Roman',serif;background:var(--bg);color:var(--ink);line-height:1.55}
header.top{background:var(--accent);color:#f7f3ec;padding:14px 24px;display:flex;gap:18px;align-items:baseline;flex-wrap:wrap}
header.top .brand{font-weight:700;font-size:1.05rem;color:#f7f3ec;text-decoration:none}
header.top nav a{color:#f7f3ec;opacity:.8;text-decoration:none;font-size:.9rem;margin-right:14px}
header.top nav a:hover{opacity:1}
main{max-width:820px;margin:0 auto;padding:28px 20px 40px}
h1{font-size:1.7rem;line-height:1.25;margin:.2em 0 .3em}
.muted{color:var(--ink2)}
.badge{display:inline-block;background:var(--bg2);border:1px solid var(--border);border-radius:12px;padding:2px 12px;font-size:.8rem;color:var(--ink2);margin-right:8px}
.verse-line{margin:26px 0}
.verse-line .dev{font-size:1.55rem;line-height:1.7}
.verse-line .iast{font-family:ui-monospace,'JetBrains Mono',monospace;color:var(--ink2);font-size:.95rem}
svg.wave{width:100%;max-width:640px;height:auto;margin-top:8px}
.transl{background:var(--card);border:1px solid var(--border);border-radius:10px;padding:14px 18px;margin:14px 0}
.transl .lang{font-size:.72rem;letter-spacing:.12em;text-transform:uppercase;color:var(--gold)}
.transl .attrib{font-size:.78rem;color:var(--ink2);margin-top:8px}
table.glosses{border-collapse:collapse;width:100%;font-size:.9rem;margin:12px 0}
table.glosses th,table.glosses td{border:1px solid var(--border);padding:6px 10px;text-align:left;vertical-align:top}
table.glosses th{background:var(--bg2)}
.cta-footer{margin:36px 0 8px;padding:20px 22px;background:var(--card);border:1px solid var(--border);border-radius:12px;display:flex;gap:14px;align-items:center;flex-wrap:wrap}
.cta-btn{background:var(--accent);color:#fff;padding:10px 18px;border-radius:8px;text-decoration:none;font-size:.95rem}
.cta-hint{color:var(--ink2);font-size:.85rem}
.cta-link{color:var(--accent);font-size:.9rem}
footer.site{max-width:820px;margin:0 auto;padding:10px 20px 30px;color:var(--ink2);font-size:.8rem}
.toolcard{background:var(--card);border:1px solid var(--border);border-radius:12px;padding:18px 22px;margin:16px 0}
.toolcard h2{margin:0 0 6px;font-size:1.15rem}.toolcard h2 a{color:var(--accent);text-decoration:none}
.verse-grid{display:grid;grid-template-columns:repeat(auto-fill,minmax(230px,1fr));gap:12px;margin:14px 0}
.verse-grid a{display:block;background:var(--card);border:1px solid var(--border);border-radius:10px;padding:10px 12px;text-decoration:none;color:var(--ink);font-size:.88rem}
.verse-grid a:hover{border-color:var(--gold)}
.verse-grid .m{color:var(--ink2);font-size:.75rem}
textarea{width:100%;min-height:110px;font-size:1.15rem;padding:12px;border:1px solid var(--border);border-radius:8px;font-family:inherit;background:var(--card)}
button.go{background:var(--accent);color:#fff;border:0;border-radius:8px;padding:10px 22px;font-size:1rem;cursor:pointer;margin-top:10px}
select{padding:8px;border:1px solid var(--border);border-radius:8px;background:var(--card);font-size:.95rem}
.result{margin-top:18px}.result .label{font-size:1.25rem;font-weight:700;color:var(--accent)}
.msg{color:var(--accent);margin-top:10px}
`;

function pageShell({ lang = 'en', title, description, canonical, body, campaign, headExtra = '', hub = '../' }) {
  return `<!DOCTYPE html>
<html lang="${lang}">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>${esc(title)}</title>
<meta name="description" content="${esc(description)}">
<link rel="canonical" href="${canonical}">
${headExtra}<style>${PAGE_CSS}</style>
</head>
<body>
<header class="top">
  <a class="brand" href="../../">Sanskrit Karaoke</a>
  <nav><a href="../../catalogue.html">Verse catalogue</a><a href="${hub}">Free tools</a></nav>
</header>
<main>
${body}
${ctaFooter(campaign)}
</main>
<footer class="site">SanskritKaraoke · Общество ревнителей санскрита · <a href="../../index.html">Open the trainer</a></footer>
</body>
</html>
`;
}

const written = new Map(); // rel path → content
function emit(rel, content) {
  written.set(rel, content);
  const p = join(SITE, rel);
  mkdirSync(dirname(p), { recursive: true });
  writeFileSync(p, content);
}

// ── verse landing pages ──────────────────────────────────────────────────────

const shippedRu = new Set(), shippedEn = new Set();

for (const v of verses) {
  // danda is display-only — the app's pipeline splits padas on it before
  // syllabifying, so the wave/count paths get the stripped text
  const iast1 = devToIast(stripDanda(v.s1dev || v.s1));
  const iast2 = devToIast(stripDanda(v.s2dev || v.s2));
  if (!iast1.trim()) throw new Error(`${v.id}: empty IAST after transliteration`);
  const trs = publishableTranslations(v);
  for (const t of trs) {
    if (t.lang === 'ru') shippedRu.add(v.id);
    if (t.lang === 'en') shippedEn.add(v.id);
  }

  const translationsHtml = trs.map(t => {
    const attrib = [];
    if (t.rights?.attribution) attrib.push(esc(t.rights.attribution));
    if (t.rights?.source) attrib.push(`Source: ${esc(t.rights.source)}`);
    if (t.rights?.rights_holder) attrib.push(esc(t.rights.rights_holder));
    return `<div class="transl" lang="${t.lang}"><div class="lang">${esc(LANG_LABEL[t.lang] || t.lang)}</div>
<div>${esc(t.text)}</div>
${attrib.length ? `<div class="attrib">${attrib.join(' · ')}</div>` : ''}</div>`;
  }).join('\n');

  let glossesHtml = '';
  if (v.glosses?.length) {
    const rows = v.glosses.map(g =>
      `<tr><td lang="sa">${esc(g.dev || '')}</td><td>${esc(g.sa || '')}</td><td>${esc(g.gloss_en || '')}</td><td>${esc(g.ru || '')}</td></tr>`).join('\n');
    glossesHtml = `<h2>Word-by-word glosses</h2>
<table class="glosses"><tr><th>Devanagari</th><th>IAST</th><th>EN</th><th>RU</th></tr>
${rows}</table>
<div class="muted" style="font-size:.8rem">${esc(v.gloss_source?.rights_note || '')}</div>`;
  }

  const syls1 = syllabifyIast(iast1), syls2 = syllabifyIast(iast2);

  const descBits = [`“${v.title.en}” — a Sanskrit śloka in ${v.meter} metre`];
  if (v.glosses?.length) descBits.push('word-by-word glosses');
  if (trs.some(t => t.lang === 'en')) descBits.push('English translation');
  if (trs.some(t => t.lang === 'ru')) descBits.push('русский перевод');
  descBits.push('IAST transliteration and the singable syllable wave diagram. Free tool by SanskritKaraoke.');

  const jsonld = JSON.stringify({
    '@context': 'https://schema.org',
    '@type': 'CreativeWork',
    name: v.title.en,
    alternativeHeadline: v.title.ru,
    inLanguage: 'sa',
    genre: v.meter,
    keywords: (v.tags || []).join(', '),
    url: `${BASE}/verse/${v.id}/`,
    isPartOf: { '@type': 'WebSite', name: 'SanskritKaraoke', url: `${BASE}/` },
  });

  const body = `
<p class="muted"><a href="../../tools/" style="color:inherit">← Free tools</a></p>

<h1>${esc(v.title.en)}</h1>
<p class="muted">${esc(v.title.ru)}</p>
<p><span class="badge">metre: ${esc(v.meter)} (anuṣṭubh)</span><span class="badge">${syls1.length} + ${syls2.length} syllables (4 × 8 padas)</span>${v.difficulty ? `<span class="badge">difficulty ${esc(v.difficulty)}/5</span>` : ''}${(v.tags || []).map(t => `<span class="badge">${esc(t)}</span>`).join('')}</p>
<div class="verse-line" lang="sa"><div class="dev">${esc(v.s1dev || v.s1)}</div><div class="iast">${esc(iast1)}</div>${waveSvg(iast1)}</div>
<div class="verse-line" lang="sa"><div class="dev">${esc(v.s2dev || v.s2)}</div><div class="iast">${esc(iast2)}</div>${waveSvg(iast2)}</div>
${v.author ? `<p class="muted">Melody: ${esc(v.author.melody || '—')} · transcription: ${esc(v.author.transcription || '—')}</p>` : ''}
${translationsHtml}
${glossesHtml}
<p><a class="cta-btn" style="background:var(--gold)" href="../../index.html">Open this verse in the trainer →</a></p>`;

  const description = descBits.join(', ');
  emit(`verse/${v.id}/index.html`, pageShell({
    title: `${v.title.en} — Sanskrit śloka, ${v.meter} metre | SanskritKaraoke`,
    description: description.endsWith('.') ? description : description + '.',
    canonical: `${BASE}/verse/${v.id}/`,
    body,
    campaign: `verse-${v.id}`,
    hub: '../../tools/',
    headExtra: `<script type="application/ld+json">${jsonld}</script>`,
  }));
}

// ── tool pages ────────────────────────────────────────────────────────────────

emit('tools/meter-detector/assets/meter.js', meterJs);
emit('tools/encoding-converter/assets/schemes.js', schemesJs);
emit('tools/assets/translit.js', readFileSync(join(ROOT, 'src/core/translit.js'), 'utf8'));

emit('tools/meter-detector/index.html', pageShell({
  title: 'Sanskrit Metre Detector — paste a śloka, see the wave | SanskritKaraoke',
  description: 'Paste any Sanskrit śloka and identify its metre — anuṣṭubh, vasantatilakā, śārdūlavikrīḍita, sragdharā and 100+ more — with a guru/laghu syllable wave diagram. Free tool.',
  canonical: `${BASE}/tools/meter-detector/`,
  campaign: 'meter-detector',
  body: `
<h1>Sanskrit metre detector</h1>
<p>Paste a śloka in Devanagari or IAST. The detector syllabifies it, weighs every syllable (guru heavy / laghu light), draws the wave and names the metre.</p>
<textarea id="inp" placeholder="योगस्थः कुरु कर्माणि सङ्गं त्यक्त्वा धनञ्जय ।&#10;सिद्ध्यसिद्ध्योः समो भूत्वा समत्वं योग उच्यते ॥"></textarea>
<button class="go" id="go">Detect metre</button>
<div class="msg" id="msg"></div>
<div class="result" id="out"></div>
<script type="module">
import { devToIast, syllabifyIast } from '../../assets/translit.js';
import { identifyMeterLocal } from './assets/meter.js';
const $ = id => document.getElementById(id);
function waveSvg(lineIast) {
  const syls = syllabifyIast(lineIast);
  if (!syls.length) return '';
  const W = Math.max(240, syls.length * 44 + 40), H = 96, step = (W - 40) / syls.length;
  let pts = '', labels = '', dots = '';
  syls.forEach((s, i) => {
    const x = 20 + step * i + step / 2, guru = s.type === 'guru';
    const y = guru ? 14 : 62;
    pts += x + ',' + y + ' ';
    labels += '<text x="' + x + '" y="88" text-anchor="middle" font-size="13" fill="' + (guru ? '#8B0000' : '#2C4A1E') + '" font-family="ui-monospace,monospace">' + s.syl + '</text>';
    dots += '<circle cx="' + x + '" cy="' + y + '" r="4.5" fill="' + (guru ? '#8B0000' : '#2C4A1E') + '"/>';
  });
  return '<svg viewBox="0 0 ' + W + ' ' + H + '" style="width:100%;max-width:640px"><polyline points="' + pts.trim() + '" fill="none" stroke="#b07c18" stroke-width="2"/>' + dots + labels + '</svg>';
}
$('go').onclick = () => {
  $('msg').textContent = ''; $('out').innerHTML = '';
  const raw = $('inp').value.trim();
  if (!raw) { $('msg').textContent = 'Paste a verse first.'; return; }
  // devToIast passes non-Devanagari through, so IAST pasted as-is still syllabifies
  const lines = raw.split(/[।॥\\n]+/).map(s => s.trim()).filter(Boolean);
  if (lines.length < 2) { $('msg').textContent = 'Need at least two padas (split by । or ॥).'; return; }
  const iast = lines.map(l => devToIast(l));
  const syls = iast.map(l => syllabifyIast(l));
  const weights = syls.map(ss => ss.map(s => s.type === 'guru' ? 'g' : 'l').join(''));
  const w1 = weights.length === 4 ? weights[0] + weights[1] : weights[0];
  const w2 = weights.length === 4 ? weights[2] + weights[3] : weights[1];
  const sy1 = (syls.length === 4 ? [...syls[0], ...syls[1]] : syls[0]).map(o => o.syl);
  const sy2 = (syls.length === 4 ? [...syls[2], ...syls[3]] : syls[1]).map(o => o.syl);
  const r = identifyMeterLocal(w1, w2, sy1, sy2);
  let html = '<div class="label">' + r.label + '</div>';
  html += '<p class="muted" style="font-family:ui-monospace,monospace">' + w1 + ' / ' + w2 + '</p>';
  iast.forEach((l, i) => { html += '<div>' + waveSvg(l) + '</div>'; });
  $('out').innerHTML = html;
};
</script>`,
}));

emit('tools/encoding-converter/index.html', pageShell({
  title: 'Sanskrit Transliteration Converter — Devanagari ↔ IAST | SanskritKaraoke',
  description: 'Convert Sanskrit text between Devanagari and IAST. Auto-detects IAST, Harvard-Kyoto, ITRANS, SLP, Velthuis and WX input. Free online tool.',
  canonical: `${BASE}/tools/encoding-converter/`,
  campaign: 'encoding-converter',
  body: `
<h1>Sanskrit transliteration converter</h1>
<p>Type or paste Sanskrit in Devanagari or any common romanization (IAST, Harvard-Kyoto, ITRANS, SLP, Velthuis, WX — detected automatically) and get Devanagari and IAST.</p>
<textarea id="inp" placeholder="yogasthaḥ kuru karmāṇi saṅgaṃ tyaktvā dhanañjaya"></textarea>
<button class="go" id="go">Convert</button>
<div class="msg" id="msg"></div>
<div class="result" id="out"></div>
<script type="module">
import { devToIast } from '../../assets/translit.js';
import { detectScheme, transliterateToDev, SCHEME_NAMES } from './assets/schemes.js';
const $ = id => document.getElementById(id);
$('go').onclick = () => {
  $('msg').textContent = ''; $('out').innerHTML = '';
  const t = $('inp').value.trim();
  if (!t) { $('msg').textContent = 'Paste some text first.'; return; }
  const scheme = detectScheme(t);
  const dev = transliterateToDev(t, scheme);
  const iast = devToIast(dev);
  const row = (name, val, lang) => '<div class="transl"' + (lang ? ' lang="' + lang + '"' : '') + '><div class="lang">' + name + '</div><div style="font-size:1.2rem">' + val + '</div></div>';
  let html = row('Detected input: ' + (SCHEME_NAMES[scheme] || scheme), t.replace(/</g, '&lt;'));
  html += row('Devanagari देवनागरी', dev.replace(/</g, '&lt;'), 'sa');
  html += row('IAST', iast.replace(/</g, '&lt;'));
  $('out').innerHTML = html;
};
</script>`,
}));

// ── tools hub ─────────────────────────────────────────────────────────────────

const verseCards = verses.map(v =>
  `<a href="../../verse/${v.id}/">${esc(v.title.en)}<div class="m">${esc(v.meter)} · ${esc((v.tags || []).join(', '))}</div></a>`).join('\n');

emit('tools/index.html', pageShell({
  title: 'Free Sanskrit Tools — metre detector, transliteration, 58 ślokas | SanskritKaraoke',
  description: 'Free Sanskrit tools: paste-a-śloka metre detector with a guru/laghu wave diagram, Devanagari ↔ IAST transliteration converter, and a library of ślokas with IAST, translations and glosses.',
  canonical: `${BASE}/tools/`,
  campaign: 'tools-hub',
  body: `
<h1>Free Sanskrit tools</h1>
<p>Learn Sanskrit through song: every tool is free and works right in the browser.</p>
<div class="toolcard"><h2><a href="meter-detector/">Metre detector</a></h2>
<p class="muted">Paste a śloka — see its metre, the guru/laghu weights and the singable wave diagram.</p></div>
<div class="toolcard"><h2><a href="encoding-converter/">Transliteration converter</a></h2>
<p class="muted">Devanagari ↔ IAST, with auto-detection of Harvard-Kyoto, ITRANS, SLP, Velthuis and WX input.</p></div>
<h2>Śloka library</h2>
<p class="muted">${verses.length} verses with Devanagari, IAST, the wave diagram, translations and glosses.</p>
<div class="verse-grid">
${verseCards}
</div>`,
}));

// ── sitemap + robots ──────────────────────────────────────────────────────────

const urls = [
  { loc: `${BASE}/tools/`, pri: '0.9' },
  { loc: `${BASE}/tools/meter-detector/`, pri: '0.9' },
  { loc: `${BASE}/tools/encoding-converter/`, pri: '0.9' },
  ...verses.map(v => ({ loc: `${BASE}/verse/${v.id}/`, pri: '0.7' })),
];
emit('sitemap.xml', `<?xml version="1.0" encoding="UTF-8"?>
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
${urls.map(u => `  <url><loc>${u.loc}</loc><lastmod>${TODAY_ISO}</lastmod><priority>${u.pri}</priority></url>`).join('\n')}
</urlset>
`);
emit('robots.txt', `User-agent: *\nAllow: /\nSitemap: ${BASE}/sitemap.xml\n`);

// ── self-checks (exit 1 on any failure) ──────────────────────────────────────

let failures = 0;
const check = (name, ok, detail = '') => {
  console.log(`${ok ? 'PASS' : 'FAIL'}  ${name}${detail ? ' — ' + detail : ''}`);
  if (!ok) failures++;
};

check('verse page per corpus file', verses.every(v => written.has(`verse/${v.id}/index.html`)),
  `${verses.length} verses`);
check('sitemap covers every emitted page', urls.length === 3 + verses.length, `${urls.length} urls`);
check('rights gating: RU shipped', shippedRu.size === 13, `got ${shippedRu.size}, want 13 (10 own-work + 3 cleared)`);
check('rights gating: EN shipped', shippedEn.size === 3, `got ${shippedEn.size}, want 3 (public-domain)`);

// canary: generated modules import + identify bhg_2_48 as anuṣṭubh
const { identifyMeterLocal } = await import('../site/tools/meter-detector/assets/meter.js');
const { detectScheme } = await import('../site/tools/encoding-converter/assets/schemes.js');
const bhg = verses.find(v => v.id === 'bhg_2_48');
const biast = [devToIast(stripDanda(bhg.s1dev)), devToIast(stripDanda(bhg.s2dev))];
const bsyls = biast.map(l => syllabifyIast(l));
const bw = bsyls.map(ss => ss.map(s => s.type === 'guru' ? 'g' : 'l').join(''));
const ident = identifyMeterLocal(bw[0], bw[1], bsyls[0].map(o => o.syl), bsyls[1].map(o => o.syl));
check('canary bhg_2_48 half-verses 16+16', bsyls[0].length === 16 && bsyls[1].length === 16,
  `${bsyls[0].length}+${bsyls[1].length}`);
check('canary bhg_2_48 → anuṣṭubh', /anuṣṭubh/.test(ident.label), ident.label);
check('canary IAST non-empty line 1', /yogasth/.test(biast[0]) || biast[0].length > 10, biast[0]);
check('canary scheme detect diacritic IAST', detectScheme('yogasthaḥ kuru karmāṇi') === 'IAST',
  detectScheme('yogasthaḥ kuru karmāṇi'));
check('canary scheme detect plain ASCII → HK', detectScheme('yogasthah kuru karmani') === 'HK',
  detectScheme('yogasthah kuru karmani'));

// internal link check: every relative href/src resolves to an emitted file or a
// known repo-root page (deployed by pages.yml from the repo root)
const rootPages = new Set(['index.html', 'catalogue.html', 'student.html', 'progress.html', 'mastery.html', 'manifest.json', 'sw.js']);
let badLinks = [];
for (const [rel, html] of written) {
  if (!rel.endsWith('.html')) continue;
  const relParts = rel.split('/').slice(0, -1);
  for (const m of html.matchAll(/(?:href|src)="([^"]+)"/g)) {
    const href = m[1];
    if (/^(https?:|#|mailto:|data:)/.test(href)) continue;
    const bare = href.split('?')[0].split('#')[0];
    const ups = (bare.match(/\.\.\//g) || []).length;
    const tail = bare.replace(/^(\.\.\/)+/, '').replace(/\/+$/, '');
    const from = relParts.slice(0, relParts.length - ups);
    let target = [...from, ...tail.split('/').filter(Boolean)].join('/');
    if (!/\.[a-z]+$/i.test(tail)) {
      // extension-less target — a directory link, resolves to its index page
      target = target ? target + '/index.html' : 'index.html';
      if (written.has(target)) continue;
      if (target === 'index.html' && rootPages.has('index.html')) continue;
      badLinks.push(`${rel} → ${href} (resolved ${target})`);
      continue;
    }
    if (written.has(target)) continue;
    if (!target.includes('/') && rootPages.has(target)) continue;
    badLinks.push(`${rel} → ${href} (resolved ${target})`);
  }
}
check('all internal links resolve', badLinks.length === 0, badLinks.slice(0, 5).join(' | '));

if (failures) {
  console.error(`\n${failures} check(s) FAILED`);
  process.exit(1);
}
console.log(`\nAll checks passed — ${written.size} files under site/`);
